// Code generated by goctl. DO NOT EDIT.
// Source: bspick.proto

package server

import (
	"context"

	"bspick/rpc/internal/logic"
	"bspick/rpc/internal/svc"
	"bspick/rpc/types/bspick"
)

type BspickServer struct {
	svcCtx *svc.ServiceContext
	bspick.UnimplementedBspickServer
}

func NewBspickServer(svcCtx *svc.ServiceContext) *BspickServer {
	return &BspickServer{
		svcCtx: svcCtx,
	}
}

func (s *BspickServer) GetData(ctx context.Context, in *bspick.GetDataReq) (*bspick.GetDataResp, error) {
	l := logic.NewGetDataLogic(ctx, s.svcCtx)
	return l.GetData(in)
}
