// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: bspick.proto

package bspick

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BspickClient is the client API for Bspick service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BspickClient interface {
	GetData(ctx context.Context, in *GetDataReq, opts ...grpc.CallOption) (*GetDataResp, error)
}

type bspickClient struct {
	cc grpc.ClientConnInterface
}

func NewBspickClient(cc grpc.ClientConnInterface) BspickClient {
	return &bspickClient{cc}
}

func (c *bspickClient) GetData(ctx context.Context, in *GetDataReq, opts ...grpc.CallOption) (*GetDataResp, error) {
	out := new(GetDataResp)
	err := c.cc.Invoke(ctx, "/bspick.Bspick/getData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BspickServer is the server API for Bspick service.
// All implementations must embed UnimplementedBspickServer
// for forward compatibility
type BspickServer interface {
	GetData(context.Context, *GetDataReq) (*GetDataResp, error)
	mustEmbedUnimplementedBspickServer()
}

// UnimplementedBspickServer must be embedded to have forward compatible implementations.
type UnimplementedBspickServer struct {
}

func (UnimplementedBspickServer) GetData(context.Context, *GetDataReq) (*GetDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedBspickServer) mustEmbedUnimplementedBspickServer() {}

// UnsafeBspickServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BspickServer will
// result in compilation errors.
type UnsafeBspickServer interface {
	mustEmbedUnimplementedBspickServer()
}

func RegisterBspickServer(s grpc.ServiceRegistrar, srv BspickServer) {
	s.RegisterService(&Bspick_ServiceDesc, srv)
}

func _Bspick_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BspickServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bspick.Bspick/getData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BspickServer).GetData(ctx, req.(*GetDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Bspick_ServiceDesc is the grpc.ServiceDesc for Bspick service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bspick_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bspick.Bspick",
	HandlerType: (*BspickServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getData",
			Handler:    _Bspick_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bspick.proto",
}
