// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: bspick.proto

package bspick

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 城市
	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	// 语言
	Lan string `protobuf:"bytes,2,opt,name=lan,proto3" json:"lan,omitempty"`
	// 最低
	MinK int32 `protobuf:"varint,3,opt,name=minK,proto3" json:"minK,omitempty"`
	// 活跃度 1-刚刚 2-今日 3-本周 4-本月 5-其它
	Active int32 `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *GetDataReq) Reset() {
	*x = GetDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bspick_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataReq) ProtoMessage() {}

func (x *GetDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_bspick_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataReq.ProtoReflect.Descriptor instead.
func (*GetDataReq) Descriptor() ([]byte, []int) {
	return file_bspick_proto_rawDescGZIP(), []int{0}
}

func (x *GetDataReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetDataReq) GetLan() string {
	if x != nil {
		return x.Lan
	}
	return ""
}

func (x *GetDataReq) GetMinK() int32 {
	if x != nil {
		return x.MinK
	}
	return 0
}

func (x *GetDataReq) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

type GetDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*GetDataResp_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *GetDataResp) Reset() {
	*x = GetDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bspick_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResp) ProtoMessage() {}

func (x *GetDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_bspick_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResp.ProtoReflect.Descriptor instead.
func (*GetDataResp) Descriptor() ([]byte, []int) {
	return file_bspick_proto_rawDescGZIP(), []int{1}
}

func (x *GetDataResp) GetNodes() []*GetDataResp_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetDataResp_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Num  int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GetDataResp_Node) Reset() {
	*x = GetDataResp_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bspick_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataResp_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResp_Node) ProtoMessage() {}

func (x *GetDataResp_Node) ProtoReflect() protoreflect.Message {
	mi := &file_bspick_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResp_Node.ProtoReflect.Descriptor instead.
func (*GetDataResp_Node) Descriptor() ([]byte, []int) {
	return file_bspick_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDataResp_Node) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDataResp_Node) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_bspick_proto protoreflect.FileDescriptor

var file_bspick_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x73, 0x70, 0x69, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x73, 0x70, 0x69, 0x63, 0x6b, 0x22, 0x5e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69,
	0x6e, 0x4b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x4b, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x6b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x73, 0x70, 0x69, 0x63, 0x6b, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0x2c, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x32, 0x3c, 0x0a, 0x06, 0x42, 0x73, 0x70, 0x69, 0x63, 0x6b, 0x12, 0x32, 0x0a,
	0x07, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x2e, 0x62, 0x73, 0x70, 0x69, 0x63,
	0x6b, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x62,
	0x73, 0x70, 0x69, 0x63, 0x6b, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x62, 0x73, 0x70, 0x69, 0x63, 0x6b, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bspick_proto_rawDescOnce sync.Once
	file_bspick_proto_rawDescData = file_bspick_proto_rawDesc
)

func file_bspick_proto_rawDescGZIP() []byte {
	file_bspick_proto_rawDescOnce.Do(func() {
		file_bspick_proto_rawDescData = protoimpl.X.CompressGZIP(file_bspick_proto_rawDescData)
	})
	return file_bspick_proto_rawDescData
}

var file_bspick_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bspick_proto_goTypes = []interface{}{
	(*GetDataReq)(nil),       // 0: bspick.GetDataReq
	(*GetDataResp)(nil),      // 1: bspick.GetDataResp
	(*GetDataResp_Node)(nil), // 2: bspick.GetDataResp.Node
}
var file_bspick_proto_depIdxs = []int32{
	2, // 0: bspick.GetDataResp.nodes:type_name -> bspick.GetDataResp.Node
	0, // 1: bspick.Bspick.getData:input_type -> bspick.GetDataReq
	1, // 2: bspick.Bspick.getData:output_type -> bspick.GetDataResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bspick_proto_init() }
func file_bspick_proto_init() {
	if File_bspick_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bspick_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bspick_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bspick_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataResp_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bspick_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bspick_proto_goTypes,
		DependencyIndexes: file_bspick_proto_depIdxs,
		MessageInfos:      file_bspick_proto_msgTypes,
	}.Build()
	File_bspick_proto = out.File
	file_bspick_proto_rawDesc = nil
	file_bspick_proto_goTypes = nil
	file_bspick_proto_depIdxs = nil
}
